### ISSUE TITLE
Other entries

### ISSUE THREAD

**Issue by monfera** [michelpereira/gamesofcoding#12]
How about kid games (or casual games) like [LightBot](https://lightbot.com/), Bee-Bot, Cato's Hike etc., and in general, what's the scope of this collection? I guess 'teach you a programming language' and 'teach you programming' aren't the same goals. On one end of the spectrum there are games that teach commercially successful languages while playing, and on the other, games whose mechanics are inspired by coding such as [Recursed](http://store.steampowered.com/app/497780/) which was inspired by functional progamming. There's a lot of room for teaching programming via games, and teaching a mainstream language with that sounds like a niche as the real focus could be on teaching concepts, e.g. in functional programming, linear algebra, or programming behaviors.

**Comment by crclark96** [comment]
The contribution guidelines encourage rearranging some of the entries into categories. You could make a separate section for children's games, functional programming, etc.

**Comment by michelpereira** [comment]
@monfera I see that you know a lot of kid games, please do a fork and rearrange them into a Kids category. Thanks.

**Comment by veganjay** [comment]
@monfera There is also several other similar kids games on [awesome programing for kids](https://github.com/HollyAdele/awesome-programming-for-kids)
