### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by schas002** [michelpereira/gamesofcoding#32]
1. Since when did the list become half-awesome? :3 
2. Even the issue tracker asks to read the guidelines for contributing, which don't say anything about issues.

**Comment by michelpereira** [comment]
1. Can you elaborate more?
2. Using issues is an easy way to interact with the community to understand the needs, it's all about conversation ;)

**Comment by schas002** [comment]
For 1), the list repo name was previously `michelpereira/gamesofcoding`, and recently, the name became <code>michelpereira/<i>awesome-</i>gamesofcoding</code>.

**Comment by michelpereira** [comment]
1) I created the repository and after reading the awesome list I thought that it was good to change the name to match the template.
