### ISSUE TITLE
Categories based on languages?

### ISSUE THREAD

**Issue by impressivewebs** [michelpereira/gamesofcoding#37]
Nice list but it might be useful to categorize it based on languages...? E.g. I want to look for front-end coding games, but there's no easy to see all of them other than doing CTRL-F on the page and looking for keywords.

**Comment by michelpereira** [comment]
Hi, please check the repository again because @crclark96 did a good work on classifying the games with its languages.

Thanks

**Comment by impressivewebs** [comment]
Ah yes, that's much better. Thanks!
