### ISSUE TITLE
Could I do some changes in the list?

### ISSUE THREAD

**Issue by mdtrooper** [michelpereira/gamesofcoding#46]
I love your README.md . But I want to sort and added more categories. The first, I want to separate the "open source" games and "close source" game in two list into this file. And add other things.

Does it sound good for you?

Regards.

**Comment by michelpereira** [comment]
Hi, there. I think that the list is so small to have a differentiation on open source and closed source games.
How do you see it sorted?
Do you have any example of categories that you think that will be great to add?

**Comment by mdtrooper** [comment]
Hi.

Good answer. Well, there are two reasons of separate close source and open source games. First reason is the price, not for one person, I say it for a class room or school. And the other reason...may be you are smelling...yes, I am a free software fanatic...hahaha 😆 .

And the question about new categories:
- open source
  - educacional
    - language
        -...
  - games
    - language
       -...
- close source
  - educacional
    - language
        -...
  - games
    - language
       -...
 - Other resources

Regards.

**Comment by michelpereira** [comment]
Good idea, please submit a patch and I'll merge it for you.
Thanks!

**Comment by mdtrooper** [comment]
Hi. I made the pull request in https://github.com/michelpereira/awesome-games-of-coding/pull/51 . 

Thanks :beers:

**Comment by michelpereira** [comment]
Need to update the list to be accepted at the awesome lists. The new way that we're doing doesn't have space for this proposal.
I appreciate your collaboration and keep on looking on new suggestions of games.
Thanks.
